# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
c_cumema <- function(X, days, n) {
    .Call('VSR_c_cumema', PACKAGE = 'VSR', X, days, n)
}

#' @export
c_ema <- function(X, days, n) {
    .Call('VSR_c_ema', PACKAGE = 'VSR', X, days, n)
}

#' @export
c_ema_lin <- function(X, days, n) {
    .Call('VSR_c_ema_lin', PACKAGE = 'VSR', X, days, n)
}

#' @export
c_ediversity <- function(X, N, n) {
    .Call('VSR_c_ediversity', PACKAGE = 'VSR', X, N, n)
}

#' @export
c_cum_unique_count <- function(X, N) {
    .Call('VSR_c_cum_unique_count', PACKAGE = 'VSR', X, N)
}

c_rdmean_pow <- function(x, w, p) {
    .Call('VSR_c_rdmean_pow', PACKAGE = 'VSR', x, w, p)
}

#' @export
c_apk1 <- function(k, actual, predicted) {
    .Call('VSR_c_apk1', PACKAGE = 'VSR', k, actual, predicted)
}

#' @export
c_max_ob_margin <- function(X, V) {
    .Call('VSR_c_max_ob_margin', PACKAGE = 'VSR', X, V)
}

#' @export
c_min_ob_margin <- function(X, V) {
    .Call('VSR_c_min_ob_margin', PACKAGE = 'VSR', X, V)
}

#' @export
c_ob_margin <- function(X, V, side) {
    .Call('VSR_c_ob_margin', PACKAGE = 'VSR', X, V, side)
}

top_index <- function(x, n, ascending = FALSE) {
    .Call('VSR_top_index', PACKAGE = 'VSR', x, n, ascending)
}

c_fast_paste0 <- function(str1, str2) {
    .Call('VSR_c_fast_paste0', PACKAGE = 'VSR', str1, str2)
}

c_tab <- function(x) {
    .Call('VSR_c_tab', PACKAGE = 'VSR', x)
}

#' @export
c_fill_na <- function(x) {
    .Call('VSR_c_fill_na', PACKAGE = 'VSR', x)
}

