# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
c_cumema <- function(X, days, n) {
    .Call(`_VSR_c_cumema`, X, days, n)
}

#' @export
c_ema <- function(X, days, n) {
    .Call(`_VSR_c_ema`, X, days, n)
}

#' @export
c_ema_lin <- function(X, days, n) {
    .Call(`_VSR_c_ema_lin`, X, days, n)
}

#' @export
c_ediversity <- function(X, N, n) {
    .Call(`_VSR_c_ediversity`, X, N, n)
}

#' @export
c_cum_unique_count <- function(X, N) {
    .Call(`_VSR_c_cum_unique_count`, X, N)
}

c_rdmean_pow <- function(x, w, p) {
    .Call(`_VSR_c_rdmean_pow`, x, w, p)
}

#' @export
c_apk1 <- function(k, actual, predicted) {
    .Call(`_VSR_c_apk1`, k, actual, predicted)
}

#' @export
c_ob_margin <- function(X, V, side) {
    .Call(`_VSR_c_ob_margin`, X, V, side)
}

#' @export
c_ob_exp_sum <- function(price, size, side, focals, ns) {
    .Call(`_VSR_c_ob_exp_sum`, price, size, side, focals, ns)
}

#' @export
c_roll_min <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_min`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_max <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_max`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_mean <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_mean`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_sd <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_sd`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_sum <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_sum`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_prod <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_prod`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_first <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_first`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_last <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_VSR_c_roll_last`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_quantile <- function(DATE, X, left_bound, right_bound, left_open, right_open, prob) {
    .Call(`_VSR_c_roll_quantile`, DATE, X, left_bound, right_bound, left_open, right_open, prob)
}

#' @export
c_cummin <- function(X) {
    .Call(`_VSR_c_cummin`, X)
}

#' @export
c_cummax <- function(X) {
    .Call(`_VSR_c_cummax`, X)
}

#' @export
c_buy_sell_signal <- function(X, skip, sell_entry = .3, sell_exit = .5, buy_exit = .7, buy_entry = .5) {
    .Call(`_VSR_c_buy_sell_signal`, X, skip, sell_entry, sell_exit, buy_exit, buy_entry)
}

#' @export
c_buy_sell_signal_interval <- function(X, sell1 = .3, sell2 = .5, buy1 = .7, buy2 = .5) {
    .Call(`_VSR_c_buy_sell_signal_interval`, X, sell1, sell2, buy1, buy2)
}

#' @export
c_entry_exit_signal <- function(X, exit = .5, entry = .7, buy = TRUE) {
    .Call(`_VSR_c_entry_exit_signal`, X, exit, entry, buy)
}

#' @export
c_butterfly_signal <- function(X, sell_entry = .3, buy_entry = .7) {
    .Call(`_VSR_c_butterfly_signal`, X, sell_entry, buy_entry)
}

top_index <- function(x, n, ascending = FALSE) {
    .Call(`_VSR_top_index`, x, n, ascending)
}

c_fast_paste0 <- function(str1, str2) {
    .Call(`_VSR_c_fast_paste0`, str1, str2)
}

c_tab <- function(x) {
    .Call(`_VSR_c_tab`, x)
}

#' @export
c_fill_locf_na <- function(x) {
    .Call(`_VSR_c_fill_locf_na`, x)
}

c_fill_locf_nonfinite <- function(x) {
    .Call(`_VSR_c_fill_locf_nonfinite`, x)
}

